# render.yaml
services:
  - type: web
    name: o-quvmarkaz
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn asosiy.wsgi:application"
